2021/01/16 22:04:34 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: 2021-01-16T23:04:34+01:00 [critical] Uncaught Error: syntax error, unexpected ';', expecting ')'" while reading upstream, client: 172.23.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "symfony.localhost:80"
2021/01/16 22:50:04 [error] 7#7: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 22:54:41 [error] 7#7: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:02:43 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: 2021-01-17T00:02:43+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\NewTest" in file "/var/www/symfony/tests/NewTest.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:03:14 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: 2021-01-17T00:03:14+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\NewTest" in file "/var/www/symfony/tests/NewTest.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:08:10 [error] 8#8: *2 FastCGI sent in stderr: "PHP message: 2021-01-17T00:08:10+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\Shared\Infrastructure\Doctrine\DoctrineInfrastructureTestCase" in file "/var/www/symfony/tests/Shared/Infrastructure/Doctrine/DoctrineInfrastructureTestCase.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.25.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.25.0.4:9000", host: "symfony.localhost:80"
2021/01/17 18:40:21 [error] 7#7: *34 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/17 18:53:19 [error] 7#7: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/17 19:26:06 [error] 7#7: *68 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
