2021/01/16 22:04:34 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: 2021-01-16T23:04:34+01:00 [critical] Uncaught Error: syntax error, unexpected ';', expecting ')'" while reading upstream, client: 172.23.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "symfony.localhost:80"
2021/01/16 22:50:04 [error] 7#7: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 22:54:41 [error] 7#7: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:02:43 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: 2021-01-17T00:02:43+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\NewTest" in file "/var/www/symfony/tests/NewTest.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:03:14 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: 2021-01-17T00:03:14+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\NewTest" in file "/var/www/symfony/tests/NewTest.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.24.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.24.0.4:9000", host: "symfony.localhost:80"
2021/01/16 23:08:10 [error] 8#8: *2 FastCGI sent in stderr: "PHP message: 2021-01-17T00:08:10+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Tests\Shared\Infrastructure\Doctrine\DoctrineInfrastructureTestCase" in file "/var/www/symfony/tests/Shared/Infrastructure/Doctrine/DoctrineInfrastructureTestCase.php" while importing services from resource "../../../tests/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services_test.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services_test.yaml")" while reading upstream, client: 172.25.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.25.0.4:9000", host: "symfony.localhost:80"
2021/01/17 18:40:21 [error] 7#7: *34 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/17 18:53:19 [error] 7#7: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/17 19:26:06 [error] 7#7: *68 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:03:33 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: 2021-01-17T22:03:33+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Shared\Infrastructure\Symfony\ApiResponseResource" in file "/var/www/symfony/src/S" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:03:33 [error] 7#7: *23 FastCGI sent in stderr: "hared/Infrastructure/Symfony/ApiResponseResource.php" while importing services from resource "../../../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services.yaml")" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:04:08 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: 2021-01-17T22:04:08+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Shared\Infrastructure\Symfony\ApiResponseResource" in file "/var/www/symfony/src/S" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:04:08 [error] 7#7: *23 FastCGI sent in stderr: "hared/Infrastructure/Symfony/ApiResponseResource.php" while importing services from resource "../../../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services.yaml")" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:05:08 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: 2021-01-17T22:05:08+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Shared\Infrastructure\Symfony\ApiResponseResource" in file "/var/www/symfony/src/S" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:05:08 [error] 7#7: *23 FastCGI sent in stderr: "hared/Infrastructure/Symfony/ApiResponseResource.php" while importing services from resource "../../../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services.yaml")" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "GET /itineraries99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:05:24 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: 2021-01-17T22:05:24+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Shared\Infrastructure\Symfony\ApiResponseResource" in file "/var/www/symfony/src/S" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM&name=A1 HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 21:05:24 [error] 7#7: *23 FastCGI sent in stderr: "hared/Infrastructure/Symfony/ApiResponseResource.php" while importing services from resource "../../../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services.yaml")" while reading upstream, client: 172.22.0.1, server: symfony.localhost, request: "POST /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity?XDEBUG_SESSION_START=PHPSTORM&name=A1 HTTP/1.1", upstream: "fastcgi://172.22.0.4:9000", host: "symfony.localhost:80"
2021/01/17 23:33:24 [error] 7#7: *31 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "symfony.localhost:80"
2021/01/17 23:43:41 [error] 7#7: *45 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.23.0.1, server: symfony.localhost, request: "GET /itineraries/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "symfony.localhost:80"
2021/01/18 18:36:00 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: 2021-01-18T19:36:00+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:36:01 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: 2021-01-18T19:36:01+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:36:34 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: 2021-01-18T19:36:34+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:36:35 [error] 7#7: *5 FastCGI sent in stderr: "PHP message: 2021-01-18T19:36:35+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:40:22 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2021-01-18T19:40:22+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:40:28 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2021-01-18T19:40:28+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:40:28 [error] 7#7: *16 FastCGI sent in stderr: "PHP message: 2021-01-18T19:40:28+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:43:08 [error] 7#7: *21 FastCGI sent in stderr: "PHP message: 2021-01-18T19:43:08+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 18:46:15 [error] 7#7: *27 FastCGI sent in stderr: "PHP message: 2021-01-18T19:46:15+01:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "nelmio_api_doc" (in "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml"). Looked for namespace "nelmio_api_doc", found ""framework", "doctrine", "monolog", "twig"" in /var/www/symfony/app/config/packages/nelmio_api_doc.yaml (which is loaded in resource "/var/www/symfony/app/config/packages/nelmio_api_doc.yaml")" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/18 20:05:06 [error] 7#7: *291 FastCGI sent in stderr: "PHP message: 2021-01-18T21:05:06+01:00 [critical] Uncaught Error: syntax error, unexpected '*', expecting function (T_FUNCTION) or const (T_CONST)" while reading upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost"
2021/01/18 23:06:15 [error] 7#7: *469 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/18 23:11:38 [error] 7#7: *475 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "symfony.localhost:80"
2021/01/19 16:24:04 [error] 8#8: *13 FastCGI sent in stderr: "PHP message: 2021-01-19T17:24:04+01:00 [critical] Uncaught Exception: Expected to find class "Academy\Evaluation\Application\Evaluate\EvaluateHandler" in file "/var/www/symfony/src/Evaluation/Application/Evaluate/EvaluateHandler.php" while importing services from resource "../../../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/app/config/services/services.yaml (which is loaded in resource "/var/www/symfony/app/config/services/services.yaml")" while reading upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost"
2021/01/19 22:15:52 [error] 8#8: *101 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/19 22:16:56 [error] 8#8: *101 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/19 22:52:03 [error] 9#9: *14 FastCGI sent in stderr: "PHP message: 2021-01-19T23:52:03+01:00 [critical] Uncaught Error: syntax error, unexpected ';', expecting ')'" while reading upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/19 23:22:15 [error] 9#9: *56 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/19 23:23:47 [error] 9#9: *56 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A1&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 00:03:42 [error] 9#9: *87 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 16:58:58 [error] 8#8: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 18:47:23 [error] 8#8: *40 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 18:51:36 [error] 8#8: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 19:01:15 [error] 8#8: *48 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:34:24 [error] 8#8: *149 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:36:13 [error] 8#8: *149 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:40:02 [error] 8#8: *162 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "POST /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/evaluate?activity_name=A5&XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:52:09 [error] 8#8: *175 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:53:18 [error] 8#8: *175 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 20:56:40 [error] 8#8: *175 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 22:18:02 [error] 8#8: *198 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 22:19:59 [error] 8#8: *198 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 22:22:09 [error] 8#8: *207 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 22:55:35 [error] 8#8: *266 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 23:00:53 [error] 8#8: *266 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 23:11:09 [error] 8#8: *295 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/20 23:44:12 [error] 8#8: *362 FastCGI sent in stderr: "PHP message: 2021-01-21T00:44:12+01:00 [critical] Uncaught Error: syntax error, unexpected 'Response' (T_STRING)" while reading upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/students/70f066f6-1cb7-4c45-97e2-287f0258ba02/itinerary/99f951bf-7d49-4a1a-9152-7bdee1f5ce2e/activity/next?XDEBUG_SESSION_START=PHPSTORM HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost:80"
2021/01/21 00:25:58 [error] 8#8: *424 FastCGI sent in stderr: "PHP message: 2021-01-21T01:25:58+01:00 [critical] Uncaught Exception: Invalid handler service "Academy\Student\Application\EvaluationActivityItinerary\Evaluatio" while reading upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost"
2021/01/21 00:25:58 [error] 8#8: *424 FastCGI sent in stderr: "nActivityItineraryHandler": class or interface "Academy\Student\Application\EvaluationActivityItinerary\GetNextActivityCommand" used as argument type in method "Academy\Student\Application\EvaluationActivityItinerary\EvaluationActivityItineraryHandler::__invoke()" not found" while reading upstream, client: 172.18.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "symfony.localhost"
2021/01/23 00:58:16 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2021-01-23T01:58:16+01:00 [critical] Uncaught Exception: Unable to write in the "cache" directory (/var/www/symfony/app/var/cache)" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/23 00:58:17 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2021-01-23T01:58:17+01:00 [critical] Uncaught Exception: Unable to write in the "cache" directory (/var/www/symfony/app/var/cache)" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/23 00:58:35 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2021-01-23T01:58:35+01:00 [warning] Uncaught Warning: file_put_contents(/var/www/symfony/app/var/cache/Academy_src_KernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/23 00:58:36 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2021-01-23T01:58:36+01:00 [warning] Uncaught Warning: file_put_contents(/var/www/symfony/app/var/cache/Academy_src_KernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
2021/01/23 00:58:36 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2021-01-23T01:58:36+01:00 [warning] Uncaught Warning: file_put_contents(/var/www/symfony/app/var/cache/Academy_src_KernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory" while reading upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /api/doc HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "symfony.localhost"
